.catalog:
  name: "Elasticsearch"
  version: "2.2.2-rancher1"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: es_version
      description: "Version of Elasticsearch to install."
      label: "Elasticsearch Version"
      type: "string"
      required: true
      default: "5.1.2"
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
    - variable: storage_size
      description: "Amount of storage in GB to use on data nodes for persistent storage."
      label: "Storage Size"
      type: "string"
      required: true
      default: "30"
    - variable: "kopf_port"
      label: "Public Port"
      description: "Unique public port for kopf"
      type: "int"
      default: 80
      required: true
    - variable: "java_memory"
      label: "Java Heap Size"
      description: "Allows you to set the default heap size for ES Java"
      type: "int"
      default: 2
      required: true
version: '2'
services:
  elasticsearch-masters:
    metadata:
      elasticsearch:
        yml:
          cluster.name: "${cluster_name}"
          node.name: "$${HOSTNAME}"
          node.data: "false"
          node.master: "true"
          network.host: "_site_"
  elasticsearch-datanodes:
    metadata:
      elasticsearch:
        yml:
          cluster.name: "${cluster_name}"
          node.name: "$${HOSTNAME}"
          node.data: "true"
          node.master: "false"
          http.enabled: "false"
          network.host: "_site_"
  elasticsearch-clients:
    metadata:
      elasticsearch:
        yml:
         cluster.name: "${cluster_name}"
         node.name: "$${HOSTNAME}"
         node.data: "false"
         node.master: "false"
         network.host: "_site_"
